### ISSUE TITLE
Numero de muestras para Senescencia

### ISSUE THREAD

**Issue by sofilibi** [omarbenites/traittools#1]
Estimado Omar:

He creado la columna "Senescencia" solo para probar, y deje vacías las filas que carecían de otros datos, (para que haya un n=6) sin embargo a pesar que no hay datos en estas filas de senescencia me pone un n=8.

[PTYL201207_CIPHQ_Exp1.xlsx](https://github.com/omarbenites/traittools/files/92366/PTYL201207_CIPHQ_Exp1.xlsx)

Me avisas a que se podría deber.

Muchas Gracias

atte.

S.Tejada

**Comment by sofilibi** [comment]
Ejemplito gráfico de lo que quize decir:
con el n=6 y el n=8

![hgh](https://cloud.githubusercontent.com/assets/4973956/12365383/77ab97e6-bba2-11e5-83b3-3c2dfb91ec81.png)

**Comment by omarbenites** [comment]
Lo que pasa es que el genotipo sigue presente, a pesar de que no haya valor en ese trait. Es un ejemplo muy especial (dado que si hay trait de rendimiento, por defecto debe haber traits de senecencia y tamaño de tubérculo.). Valdría revisarlo un poco más con Vilma.

**Comment by sofilibi** [comment]
Ajá, ya que en los otros casos por ejemplo ATW, el genotipo tbm está presente, sin emabrgo el n=6....

**Comment by omarbenites** [comment]
@sofilibi  now is fixed. Try with the same file.
Thanks for your review :+1:

**Comment by sofilibi** [comment]
Thank you so much!!! I'm on it =D !!!
