### ISSUE TITLE
Rangos Fuera de Valor no detectados

### ISSUE THREAD

**Issue by sofilibi** [omarbenites/traittools#2]
Estimado Omar:

No esta pintando de rojito el valor fuera de rango para "Tuber_size" que es el ejemplo que puse, sin embargo si pinta de rojito una "NA"

![ss](https://cloud.githubusercontent.com/assets/4973956/12365126/cdf73ff8-bba0-11e5-9df3-b2e2c35c318f.png)

Me avisas please a que se puede deber

atte.

S.Tejada

p.d: el libro que utilize es el mismo que adjunte antes, solo que agrege "datos no reales" para crear la columna.

**Comment by sofilibi** [comment]
Hay me voy a responder sola, es pq es con minusculas (Tub_size), sin embargo igual pinta de rojo el NA :) :)

**Comment by omarbenites** [comment]
Ha! No problem about that. Take it easy!
