### ISSUE TITLE
Decimales en los Calculos

### ISSUE THREAD

**Issue by sofilibi** [omarbenites/traittools#5]
Estimado Omar,

(jeje ya volvi de vacaciones, otra vez...testeando el HiDap) Encontré una pequeña observacion al momento de hacer los cálculos con respecto a los decimales. Ver imágen adjunta

![this](https://cloud.githubusercontent.com/assets/4973956/12760868/a9a85dde-c9b6-11e5-995e-0ca7dc5f0b63.png)

Como verás en los calculos manuales hay veces que los cálculos dan un numero exacto por lo tanto no tienen decimales (supongase en la columna E de los datos calculados a mano), y dan con decimal en los casos que no se numero exacto (en la columna D en los calculos calculados a mano). Este calculo entonces deberia ser el mismo en el HiDAP, sin embargo en el HIDAp "se pierden" los decimales de TTYNA cuando la columna TTYA es un numero exacto o tiene menos decimales, es decir esta igualando el numero de decimales para la columna TTYNA...

jiji espero que la imagen sea mas clara que mi explicacion... :(

Saludoss!!!

**Comment by omarbenites** [comment]
Genial soft :+1: !.
Por otro lado, me parece ese tipo de calcula esta estrechamente relacionado al excel en la forma como redondea los numeros. Veré un mas al respecto.
